fixes:
  - "ros_ws/src/*/free_fleet/free_fleet/::"
  - "ros_ws/src/*/free_fleet/free_fleet_adapter/::"

ignore:
  - "**/tests/*"
  - "**/tests/**/*"
  - "ros_ws/src/*/free_fleet/free_fleet_adapter/free_fleet_adapter/fleet_adapter.py"
