services:
  minimal-ros1-sim:
    image: ghcr.io/open-rmf/free_fleet/minimal-ros1-sim:noetic-latest
    stop_signal: SIGINT
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true

  minimal-nav1-bringup:
    image: ghcr.io/open-rmf/free_fleet/minimal-nav1-bringup:noetic-latest
    stop_signal: SIGINT
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true

  minimal-zenoh-bridge-ros1:
    image: ghcr.io/open-rmf/free_fleet/minimal-zenoh-bridge-ros1:noetic-latest
    network_mode: host
    stdin_open: true
    tty: true

  minimal-zenoh-router:
    image: eclipse/zenoh
    restart: unless-stopped
    network_mode: host
    stdin_open: true
    tty: true
    environment:
      - RUST_LOG=debug

  rmf-common:
    image: ghcr.io/open-rmf/free_fleet/free-fleet-examples:jazzy-latest
    stop_signal: SIGINT
    network_mode: host
    stdin_open: true
    tty: true
    environment:
      - ROS_DOMAIN_ID=42
    command: bash -c "ros2 launch free_fleet_examples turtlebot3_world_rmf_common.launch.xml"
